# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Czechsmix's Quest to Level Up
email: sferree567@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A site for Sam 'CzechsMix' Ferree to post thoughts and projects.
  A blog about building a more sound mind, sound body, and leveling up in life.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://czechsmix.com" # the base hostname & protocol for your site
twitter_username: NinetyOrTen
github_username:  czechsmix

# Build settings
markdown: kramdown
